[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.13.0"
store = { version = "0.1.0", path = "../store" }
util = { version = "0.1.0", path = "../util" }
